### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by kingname** [triggerdotdev/jsonhero-web#145]
```
> @jsonhero/jsonhero-web@ postinstall /home/ubuntu/jsonhero-web
> remix setup cloudflare-workers

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/jsonhero-web/node_modules/@remix-run/dev/compiler/plugins/serverRouteModulesPlugin.js:16:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/jsonhero-web/node_modules/@remix-run/dev/compiler.js:34:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @jsonhero/jsonhero-web@ postinstall: `remix setup cloudflare-workers`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @jsonhero/jsonhero-web@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-01-22T02_44_54_989Z-debug.log
```

**Comment by duyubing** [comment]
我也遇到这个问题

**Comment by kingname** [comment]
来信已收到，我会尽快回复。

**Comment by Rayren0000** [comment]
+1 咋解决的
